In [3]:
import numpy as np
from scipy.spatial.transform import Rotation




In [70]:
# Exercise setup
K=np.array([[1000,0,300],
           [0,1000,200],
          [0,0,1]])
R1 = np.identity(3)
R2 = Rotation.from_euler('xyz',[0.7,-0.5,0.8]).as_matrix()
t1 = np.array([0,0,0])
t2 = np.array([0.2,2,1])
entri1 = np.vstack([R1.T, t1]).T
entri2 = np.vstack([R2.T, t2]).T
print(entri1)

print(entri2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]
[[ 0.61141766 -0.76384514  0.20666167  0.2       ]
 [ 0.6295392   0.31131209 -0.71187442  2.        ]
 [ 0.47942554  0.56535421  0.67121217  1.        ]]


In [54]:
# Exercise 3.1
Q = np.array([1,0.5,4,1])
q1 = K@entri1@Q
q2 = K@entri2@Q
p1 = q1[:-1]/q1[-1]
p2 = q2[:-1]/q2[-1]
print(p1)
print(p2)

[550. 325.]
[582.47256835 185.98985776]


In [35]:
# Exercise 3.2
def CrossOp(p):
    return np.array([[0,-p[2],p[1]],
                    [p[2],0,-p[0]],
                    [-p[1],p[0],0]])

p1 = np.array([16,134,11324])
p2 = np.array([1521,2163,36431])
print(CrossOp(p2)@p1)
print(np.cross(p2,p1))




[ 19612058 -16640908    169206]
[ 19612058 -16640908    169206]


In [71]:
# Exercise 3.3
# Transform from camera 1 to camera 2, so try to make camera 1 the identity

E = CrossOp(t2)@R2

F = np.linalg.inv(K.T)@E@np.linalg.inv(K)
p1 = entri1@Q
p2 = entri2@Q
q1 = K@p1
q2 = K@p2

print("Point1",p1,q1)
print("Point2",p2,q2)

print("E",E)
print("F",F)
print(p2.T@E@p1) #Close to 0
print(q2.T@F@q1) #Close to 0


Point1 [1.  0.5 4. ] [2200. 1300.    4.]
Point2 [ 1.25614176 -0.06230242  4.44695131] [2590.22714938  827.08784113    4.44695131]
E [[ 0.32931188  0.81939633  2.05429875]
 [ 0.51553255 -0.87691598  0.07241923]
 [-1.09692748  1.5899527  -0.55569822]]
F [[ 3.29311881e-07  8.19396327e-07  1.79162592e-03]
 [ 5.15532551e-07 -8.76915984e-07  9.31426656e-05]
 [-1.29882755e-03  1.51951700e-03 -1.10072682e+00]]
1.7763568394002505e-15
3.552713678800501e-15


In [118]:
# Exercise 3.4

l = F@q1
print(l/(l[-1]/-5.285))


[ 8.95627993e-03  3.66754562e-04 -5.28500000e+00]


In [119]:
# Exercise 3.5
print(q2@l)



7.105427357601002e-15


In [ ]:
# Exercise 3.6


In [ ]:
# Exercise 3.7

In [ ]:
# Exercise 3.8

In [ ]:
# Exercise 3.9

In [ ]:
# Exercise 3.10
def DrawLine(l, shape):
    #Checks where the line intersects the four sides of the image
    # and finds the two intersections that are within the frame
    def in_frame(l_im):
        q = np.cross(l.flatten(), l_im)
        q = q[:2]/q[2]
        if all(q>=0) and all(q+1<=shape[1::-1]):
            return q
    lines = [[1, 0, 0], [0, 1, 0], [1, 0, 1-shape[1]], [0, 1, 1-shape[0]]]
    P = [in_frame(l_im) for l_im in lines if in_frame(l_im) is not None]
    plt.plot(*np.array(P).T)


In [ ]:
# Exercise 3.11
def triangulate(points,projection):
    

